[package]
name = "dash_typed_cfg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dash_middle = { path = "../dash_middle" }
thiserror = "1.0.38"
bitvec = "1.0.1"
